<a href="https://colab.research.google.com/github/shaalu2408-pixel/Python-coding-challenges/blob/main/Shalini_R_day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Day 7– Data Cleaning & Stats**

# Detecting & removing duplicates.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Titanic dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.drop_duplicates(inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# **Handle inconsistent or missing data.**

# **Handle Inconsistent**

In [ ]:
df.set_index('PassengerId',inplace=True)              # PassengerID as index
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Sex']=df['Sex'].str.lower().str.strip()
df['Embarked']=df['Embarked'].str.upper().str.strip()

In [ ]:
df['Sex']=df['Sex'].str.capitalize()                      # captilize the first word of each row in Sex column
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Last_Name'] = df['Name'].str.split(',').str[0]                              # adding a new column as Last_Name
df['Title'] = df['Name'].str.extract(r',\s*([^.]*)\.')[0].str.strip()          # adding a new column as Title
df['First_Name'] = df['Name'].str.split('.').str[-1].str.strip()               # Adding a new column as First_Name
df.drop('Name', axis=1, inplace=True)                                          # delete a column Name
df['Full_Name'] = df['First_Name'] + ' ' + df['Last_Name']                      # update a column
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name,Full_Name
PassengerId,,,,,,,,,,,,,,
1,0,3,Male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr,Owen Harris,Owen Harris Braund
2,1,1,Female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),John Bradley (Florence Briggs Thayer) Cumings
3,1,3,Female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss,Laina,Laina Heikkinen
4,1,1,Female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs,Jacques Heath (Lily May Peel),Jacques Heath (Lily May Peel) Futrelle
5,0,3,Male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr,William Henry,William Henry Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,Male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev,Juozas,Juozas Montvila
888,1,1,Female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss,Margaret Edith,Margaret Edith Graham
889,0,3,Female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss,"Catherine Helen ""Carrie""","Catherine Helen ""Carrie"" Johnston"
890,1,1,Male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr,Karl Howell,Karl Howell Behr
891,0,3,Male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr,Patrick,Patrick Dooley

# **Missing Values**

In [ ]:
Embarked_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(Embarked_mode, inplace=True)
Cabin_mode = df['Cabin'].mode()[0]
df['Cabin'].fillna(Cabin_mode,inplace=True)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    object
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Ticket      891 non-null    object
 7   Fare        891 non-null    float64
 8   Cabin       891 non-null    object
 9   Embarked    891 non-null    object
 10  Last_Name   891 non-null    object
 11  Title       891 non-null    object
 12  First_Name  891 non-null    object
 13  Full_Name   891 non-null    object
dtypes: float64(2), int64(4), object(8)
memory usage: 104.4+ KB

/tmp/ipython-input-4163628502.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(Embarked_mode, inplace=True)
/tmp/ipython-input-4163628502.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(Cabin_mode,inplace=True)
/tmp/ipython-input-4163628502.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

# **Compute basic statistics: mean, median, mode, std, variance.**

In [ ]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df.mean(numeric_only=True)

Survived     0.383838
Pclass       2.308642
Age         29.699118
SibSp        0.523008
Parch        0.381594
Fare        32.204208
dtype: float64

In [ ]:
df.median(numeric_only=True)

Survived     0.000000
Pclass       3.000000
Age         29.699118
SibSp        0.000000
Parch        0.000000
Fare        14.454200
dtype: float64

In [ ]:
df.mode(numeric_only=True)

   Survived  Pclass        Age  SibSp  Parch  Fare
0         0       3  29.699118      0      0  8.05

In [ ]:
df.std(numeric_only=True)

Survived     0.486592
Pclass       0.836071
Age         13.002015
SibSp        1.102743
Parch        0.806057
Fare        49.693429
dtype: float64

In [ ]:
df.var(numeric_only=True)

Survived       0.236772
Pclass         0.699015
Age          169.052400
SibSp          1.216043
Parch          0.649728
Fare        2469.436846
dtype: float64

# **Group by categories and summarize insights.**

In [ ]:
s=df.groupby('Sex').agg(
    Survival_Rate=('Survived','mean'),
    Average_age=('Age','mean'),
    Average_Fare=('Fare','mean')
     )
print(s)

        Survival_Rate  Average_age  Average_Fare
Sex
Female       0.742038    28.216730     44.479818
Male         0.188908    30.505824     25.523893