<a href="https://colab.research.google.com/github/shaalu2408-pixel/Python-coding-challenges/blob/main/Shalini_R_day2_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Day 2– Pandas Basics**

## **Import dataset into Pandas DataFrame.**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Titanic dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# **Data Cleaning**

In [ ]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
Embarked_mode = df['Embarked'].mode()[0]
df['Embarked'].fillna(Embarked_mode, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

/tmp/ipython-input-308440543.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(Embarked_mode, inplace=True)

In [ ]:
Cabin_mode = df['Cabin'].mode()[0]
df['Cabin'].fillna(Cabin_mode,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

/tmp/ipython-input-492164639.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(Cabin_mode,inplace=True)

In [ ]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

/tmp/ipython-input-1368412104.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

# **Explore series & columns.**

In [ ]:
df.columns          # explore all columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked', 'Last_Name', 'Title', 'First_Name', 'Full_Name'],
      dtype='object')

In [ ]:
df['Fare']           # specific column as a Series

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

## **Add, update, delete columns/rows.**

In [ ]:
df['Last_Name'] = df['Name'].str.split(',').str[0]         # adding a new column as Last_Name
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley

In [ ]:
df['Title'] = df['Name'].str.extract(r',\s*([^.]*)\.')[0].str.strip()          # adding a new column as Title
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Futrelle,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Graham,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Behr,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley,Mr

In [ ]:
df['First_Name'] = df['Name'].str.split('.').str[-1].str.strip()         # Addind a new column as First_Name
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund,Mr,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen,Miss,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,Futrelle,Mrs,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen,Mr,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila,Rev,Juozas
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,Graham,Miss,Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston,Miss,"Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,Behr,Mr,Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley,Mr,Patrick

In [ ]:
df.drop('Name', axis=1, inplace=True)           # delete a column Name
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name
0,1,0,3,male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund,Mr,Owen Harris
1,2,1,1,female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer)
2,3,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen,Miss,Laina
3,4,1,1,female,35.000000,1,0,113803,53.1000,C123,S,Futrelle,Mrs,Jacques Heath (Lily May Peel)
4,5,0,3,male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen,Mr,William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila,Rev,Juozas
887,888,1,1,female,19.000000,0,0,112053,30.0000,B42,S,Graham,Miss,Margaret Edith
888,889,0,3,female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston,Miss,"Catherine Helen ""Carrie"""
889,890,1,1,male,26.000000,0,0,111369,30.0000,C148,C,Behr,Mr,Karl Howell
890,891,0,3,male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley,Mr,Patrick

In [ ]:
df['Full_Name'] = df['First_Name'] + ' ' + df['Last_Name']     # update a column
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name,Full_Name
0,1,0,3,male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund,Mr,Owen Harris,Owen Harris Braund
1,2,1,1,female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),John Bradley (Florence Briggs Thayer) Cumings
2,3,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen,Miss,Laina,Laina Heikkinen
3,4,1,1,female,35.000000,1,0,113803,53.1000,C123,S,Futrelle,Mrs,Jacques Heath (Lily May Peel),Jacques Heath (Lily May Peel) Futrelle
4,5,0,3,male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen,Mr,William Henry,William Henry Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila,Rev,Juozas,Juozas Montvila
887,888,1,1,female,19.000000,0,0,112053,30.0000,B42,S,Graham,Miss,Margaret Edith,Margaret Edith Graham
888,889,0,3,female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston,Miss,"Catherine Helen ""Carrie""","Catherine Helen ""Carrie"" Johnston"
889,890,1,1,male,26.000000,0,0,111369,30.0000,C148,C,Behr,Mr,Karl Howell,Karl Howell Behr
890,891,0,3,male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley,Mr,Patrick,Patrick Dooley

# **Set a custom index and sort.**

In [ ]:
df.set_index('PassengerId', inplace=True)               # PassengerID as index
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name,Full_Name
PassengerId,,,,,,,,,,,,,,
1,0,3,male,22.000000,1,0,A/5 21171,7.2500,B96 B98,S,Braund,Mr,Owen Harris,Owen Harris Braund
2,1,1,female,38.000000,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),John Bradley (Florence Briggs Thayer) Cumings
3,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,B96 B98,S,Heikkinen,Miss,Laina,Laina Heikkinen
4,1,1,female,35.000000,1,0,113803,53.1000,C123,S,Futrelle,Mrs,Jacques Heath (Lily May Peel),Jacques Heath (Lily May Peel) Futrelle
5,0,3,male,35.000000,0,0,373450,8.0500,B96 B98,S,Allen,Mr,William Henry,William Henry Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,211536,13.0000,B96 B98,S,Montvila,Rev,Juozas,Juozas Montvila
888,1,1,female,19.000000,0,0,112053,30.0000,B42,S,Graham,Miss,Margaret Edith,Margaret Edith Graham
889,0,3,female,29.699118,1,2,W./C. 6607,23.4500,B96 B98,S,Johnston,Miss,"Catherine Helen ""Carrie""","Catherine Helen ""Carrie"" Johnston"
890,1,1,male,26.000000,0,0,111369,30.0000,C148,C,Behr,Mr,Karl Howell,Karl Howell Behr
891,0,3,male,32.000000,0,0,370376,7.7500,B96 B98,Q,Dooley,Mr,Patrick,Patrick Dooley

In [ ]:
df.sort_values(by='Age', inplace=True)              # sorting Age column in ascending order
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Title,First_Name,Full_Name
PassengerId,,,,,,,,,,,,,,
804,1,3,male,0.42,0,1,2625,8.5167,B96 B98,C,Thomas,Master,Assad Alexander,Assad Alexander Thomas
756,1,2,male,0.67,1,1,250649,14.5000,B96 B98,S,Hamalainen,Master,Viljo,Viljo Hamalainen
470,1,3,female,0.75,2,1,2666,19.2583,B96 B98,C,Baclini,Miss,Helene Barbara,Helene Barbara Baclini
645,1,3,female,0.75,2,1,2666,19.2583,B96 B98,C,Baclini,Miss,Eugenie,Eugenie Baclini
79,1,2,male,0.83,0,2,248738,29.0000,B96 B98,S,Caldwell,Master,Alden Gates,Alden Gates Caldwell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,0,3,male,70.50,0,0,370369,7.7500,B96 B98,Q,Connors,Mr,Patrick,Patrick Connors
494,0,1,male,71.00,0,0,PC 17609,49.5042,B96 B98,C,Artagaveytia,Mr,Ramon,Ramon Artagaveytia
97,0,1,male,71.00,0,0,PC 17754,34.6542,A5,C,Goldschmidt,Mr,George B,George B Goldschmidt
852,0,3,male,74.00,0,0,347060,7.7750,B96 B98,S,Svensson,Mr,Johan,Johan Svensson
631,1,1,male,80.00,0,0,27042,30.0000,A23,S,Barkworth,Mr,Algernon Henry Wilson,Algernon Henry Wilson Barkworth